# Generated by Django 3.2.6 on 2021-08-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry_verb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='verb',
        ),
    ]
